# Generated by Django 5.0.3 on 2025-03-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0002_symbol_payout_multiplier_alter_symbol_image_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='payout_multiplier',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
